# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    adapter: postgresql
    encoding: utf8
    host: localhost
    port: 5432
    timeout: 5000
    username: "postgres"
    password: "1234"
    database: evento
    migrations_paths: db/primary/migrate
  primary_replica:
    adapter: postgresql
    encoding: utf8
    host: localhost
    port: 5432
    timeout: 5000
    username: "postgres"
    password: "1234"
    database: evento
    replica: true
    
  sec:
    adapter: mysql2
    database: campolina_sgac_2022
    username: eleva
    password: "#!Eleva#Rocks"
    host: new-sgac.c74lv3pkvchh.us-east-1.rds.amazonaws.com
    pool: 5
  sec_replica:
    adapter: mysql2
    database: campolina_sgac_2022
    username: eleva
    password: "#!Eleva#Rocks"
    host: new-sgac.c74lv3pkvchh.us-east-1.rds.amazonaws.com
    pool: 5
    replica: true

production:
  primary:
    adapter: postgresql
    encoding: utf8
    host: localhost
    port: 5432
    timeout: 5000
    #username: "postgres"
    username: "postgres"
    password: "1234"
    database: evento
    migrations_paths: db/primary/migrate
  primary_replica:
    adapter: postgresql
    encoding: utf8
    host: localhost
    port: 5432
    timeout: 5000
    #username: "postgres"
    username: "postgres"
    password: "1234"
    database: evento
    replica: true

  sec:
    adapter: mysql2
    database: campolina_sgac
    username: eleva
    password: "#!Eleva#Rocks"
    host: new-sgac.c74lv3pkvchh.us-east-1.rds.amazonaws.com
    pool: 5
  sec_replica:
    adapter: mysql2
    database: campolina_sgac
    username: eleva
    password: eleva*abc
    host: new-sgac.c74lv3pkvchh.us-east-1.rds.amazonaws.com
    pool: 5
    replica: true


    #####HOST PRODUÇÃO######
    # host: eleva-prd-01.c74lv3pkvchh.us-east-1.rds.amazonaws.com
    # port: 5432
    # timeout: 5000
    # username: "eleva_pw_prod"
    # password: "AEJ9L2xRW4Ds4a7"
    # database: eventos-ranking